// Esmaül Hüsna — Allah'ın 99 ismi.
// Arapça yazılışı, Türkçe okunuşu ve kısa, sade bir Türkçe anlam.
// Anlamlar temkinli, kısa ve genel kabul gören kaynaklara göredir; kesin fıkhî hüküm içermez.

export interface EsmaEntry {
  no: number;
  arabic: string;
  turkish: string;
  meaning: string;
}

export const ESMA_LIST: EsmaEntry[] = [
  { no: 1, arabic: "الرَّحْمٰنُ", turkish: "Er-Rahmân", meaning: "Rahmeti sonsuz, tüm yaratılmışlara merhametle davranan." },
  { no: 2, arabic: "الرَّحِيمُ", turkish: "Er-Rahîm", meaning: "Ahirette müminlere sonsuz rahmetiyle muamele eden." },
  { no: 3, arabic: "الْمَلِكُ", turkish: "El-Melik", meaning: "Bütün kâinatın gerçek sahibi ve mutlak hükümdar." },
  { no: 4, arabic: "الْقُدُّوسُ", turkish: "El-Kuddûs", meaning: "Her türlü eksiklikten uzak, mukaddes olan." },
  { no: 5, arabic: "السَّلَامُ", turkish: "Es-Selâm", meaning: "Esenlik ve barışın kaynağı, kullarını selâmete erdiren." },
  { no: 6, arabic: "الْمُؤْمِنُ", turkish: "El-Mü'min", meaning: "Güven veren, kullarına emân bahşeden." },
  { no: 7, arabic: "الْمُهَيْمِنُ", turkish: "El-Müheymin", meaning: "Her şeyi görüp gözeten, kollayan." },
  { no: 8, arabic: "الْعَزِيزُ", turkish: "El-Azîz", meaning: "Yenilmez kudret sahibi, çok üstün." },
  { no: 9, arabic: "الْجَبَّارُ", turkish: "El-Cebbâr", meaning: "İradesini her şeye geçiren, dilediğini yaptıran." },
  { no: 10, arabic: "الْمُتَكَبِّرُ", turkish: "El-Mütekebbir", meaning: "Büyüklük yalnız kendisine yaraşan." },
  { no: 11, arabic: "الْخَالِقُ", turkish: "El-Hâlik", meaning: "Her şeyi yoktan var eden yaratıcı." },
  { no: 12, arabic: "الْبَارِئُ", turkish: "El-Bâri'", meaning: "Yarattıklarını uyumlu ve kusursuz şekilde meydana getiren." },
  { no: 13, arabic: "الْمُصَوِّرُ", turkish: "El-Musavvir", meaning: "Her varlığa özgün bir suret veren." },
  { no: 14, arabic: "الْغَفَّارُ", turkish: "El-Gaffâr", meaning: "Günahları örten, çokça bağışlayan." },
  { no: 15, arabic: "الْقَهَّارُ", turkish: "El-Kahhâr", meaning: "Her şeye galip gelen, kahredici kudret sahibi." },
  { no: 16, arabic: "الْوَهَّابُ", turkish: "El-Vehhâb", meaning: "Karşılıksız ve çokça bağışta bulunan." },
  { no: 17, arabic: "الرَّزَّاقُ", turkish: "Er-Rezzâk", meaning: "Tüm canlıların rızkını veren." },
  { no: 18, arabic: "الْفَتَّاحُ", turkish: "El-Fettâh", meaning: "Kapalı olanı açan, hayır kapılarını aralayan." },
  { no: 19, arabic: "الْعَلِيمُ", turkish: "El-Alîm", meaning: "Her şeyi tüm ayrıntısıyla bilen." },
  { no: 20, arabic: "الْقَابِضُ", turkish: "El-Kâbıd", meaning: "Dilediğine daraltan, sıkan." },
  { no: 21, arabic: "الْبَاسِطُ", turkish: "El-Bâsit", meaning: "Dilediğine genişlik ve bolluk veren." },
  { no: 22, arabic: "الْخَافِضُ", turkish: "El-Hâfid", meaning: "Dilediğini alçaltan." },
  { no: 23, arabic: "الرَّافِعُ", turkish: "Er-Râfi'", meaning: "Dilediğini yücelten." },
  { no: 24, arabic: "الْمُعِزُّ", turkish: "El-Muizz", meaning: "İzzet ve şeref veren." },
  { no: 25, arabic: "الْمُذِلُّ", turkish: "El-Müzill", meaning: "Zillete düşüren, alçaltan." },
  { no: 26, arabic: "السَّمِيعُ", turkish: "Es-Semî'", meaning: "Her sesi hakkıyla işiten." },
  { no: 27, arabic: "الْبَصِيرُ", turkish: "El-Basîr", meaning: "Her şeyi hakkıyla gören." },
  { no: 28, arabic: "الْحَكَمُ", turkish: "El-Hakem", meaning: "Hükmü mutlak, adaletle hükmeden." },
  { no: 29, arabic: "الْعَدْلُ", turkish: "El-Adl", meaning: "Mutlak adalet sahibi." },
  { no: 30, arabic: "اللَّطِيفُ", turkish: "El-Latîf", meaning: "En ince işleri bilen, lütuf sahibi." },
  { no: 31, arabic: "الْخَبِيرُ", turkish: "El-Habîr", meaning: "Her şeyin iç yüzünden haberdar olan." },
  { no: 32, arabic: "الْحَلِيمُ", turkish: "El-Halîm", meaning: "Cezada acele etmeyen, yumuşak davranan." },
  { no: 33, arabic: "الْعَظِيمُ", turkish: "El-Azîm", meaning: "Sonsuz büyüklük sahibi." },
  { no: 34, arabic: "الْغَفُورُ", turkish: "El-Gafûr", meaning: "Günahları çokça bağışlayan." },
  { no: 35, arabic: "الشَّكُورُ", turkish: "Eş-Şekûr", meaning: "Az amele bile bol karşılık veren." },
  { no: 36, arabic: "الْعَلِيُّ", turkish: "El-Aliyy", meaning: "Pek yüce, her şeyden üstün olan." },
  { no: 37, arabic: "الْكَبِيرُ", turkish: "El-Kebîr", meaning: "En büyük, azameti sonsuz olan." },
  { no: 38, arabic: "الْحَفِيظُ", turkish: "El-Hafîz", meaning: "Her şeyi koruyup gözeten." },
  { no: 39, arabic: "الْمُقِيتُ", turkish: "El-Mukît", meaning: "Bedenlere ve ruhlara gıda veren." },
  { no: 40, arabic: "الْحَسِيبُ", turkish: "El-Hasîb", meaning: "Hesabı gören, kullara yeten." },
  { no: 41, arabic: "الْجَلِيلُ", turkish: "El-Celîl", meaning: "Ululuk ve heybet sahibi." },
  { no: 42, arabic: "الْكَرِيمُ", turkish: "El-Kerîm", meaning: "Karşılıksız ve bol veren, cömert." },
  { no: 43, arabic: "الرَّقِيبُ", turkish: "Er-Rakîb", meaning: "Her şeyi görüp gözeten, kontrol eden." },
  { no: 44, arabic: "الْمُجِيبُ", turkish: "El-Mucîb", meaning: "Duaları kabul eden." },
  { no: 45, arabic: "الْوَاسِعُ", turkish: "El-Vâsi'", meaning: "İlmi ve rahmeti geniş olan." },
  { no: 46, arabic: "الْحَكِيمُ", turkish: "El-Hakîm", meaning: "Hikmet sahibi, işleri hikmetle yapan." },
  { no: 47, arabic: "الْوَدُودُ", turkish: "El-Vedûd", meaning: "Kullarını çok seven ve sevilmeye layık olan." },
  { no: 48, arabic: "الْمَجِيدُ", turkish: "El-Mecîd", meaning: "Şanı yüce, şerefi sonsuz olan." },
  { no: 49, arabic: "الْبَاعِثُ", turkish: "El-Bâis", meaning: "Ölüleri dirilten." },
  { no: 50, arabic: "الشَّهِيدُ", turkish: "Eş-Şehîd", meaning: "Her şeye şahit olan." },
  { no: 51, arabic: "الْحَقُّ", turkish: "El-Hakk", meaning: "Varlığı gerçek ve değişmez olan." },
  { no: 52, arabic: "الْوَكِيلُ", turkish: "El-Vekîl", meaning: "Kendisine güvenene yeten." },
  { no: 53, arabic: "الْقَوِيُّ", turkish: "El-Kaviyy", meaning: "Kudreti sonsuz olan." },
  { no: 54, arabic: "الْمَتِينُ", turkish: "El-Metîn", meaning: "Kuvveti ve iradesi çok sağlam olan." },
  { no: 55, arabic: "الْوَلِيُّ", turkish: "El-Veliyy", meaning: "Sevdiği kullarının dostu ve yardımcısı." },
  { no: 56, arabic: "الْحَمِيدُ", turkish: "El-Hamîd", meaning: "Her türlü övgüye layık olan." },
  { no: 57, arabic: "الْمُحْصِي", turkish: "El-Muhsî", meaning: "Her şeyi tek tek sayıp bilen." },
  { no: 58, arabic: "الْمُبْدِئُ", turkish: "El-Mübdi'", meaning: "Yaratmayı ilk kez başlatan." },
  { no: 59, arabic: "الْمُعِيدُ", turkish: "El-Muîd", meaning: "Yaratılışı tekrar eden." },
  { no: 60, arabic: "الْمُحْيِي", turkish: "El-Muhyî", meaning: "Hayat veren, dirilten." },
  { no: 61, arabic: "الْمُمِيتُ", turkish: "El-Mümît", meaning: "Ölümü yaratan." },
  { no: 62, arabic: "الْحَيُّ", turkish: "El-Hayy", meaning: "Ezelî ve ebedî diri olan." },
  { no: 63, arabic: "الْقَيُّومُ", turkish: "El-Kayyûm", meaning: "Kendi zatıyla var olan, her şeyi ayakta tutan." },
  { no: 64, arabic: "الْوَاجِدُ", turkish: "El-Vâcid", meaning: "Dilediğini istediği anda bulan." },
  { no: 65, arabic: "الْمَاجِدُ", turkish: "El-Mâcid", meaning: "Şanı yüce, keremi bol olan." },
  { no: 66, arabic: "الْوَاحِدُ", turkish: "El-Vâhid", meaning: "Tek olan, ortağı olmayan." },
  { no: 67, arabic: "الْأَحَدُ", turkish: "El-Ahad", meaning: "Zatında ve sıfatlarında eşsiz olan." },
  { no: 68, arabic: "الصَّمَدُ", turkish: "Es-Samed", meaning: "Hiçbir şeye muhtaç olmayan, her şey kendisine muhtaç olan." },
  { no: 69, arabic: "الْقَادِرُ", turkish: "El-Kâdir", meaning: "Her şeye gücü yeten." },
  { no: 70, arabic: "الْمُقْتَدِرُ", turkish: "El-Muktedir", meaning: "Kudreti sonsuz, dilediğini yapan." },
  { no: 71, arabic: "الْمُقَدِّمُ", turkish: "El-Mukaddim", meaning: "Dilediğini öne alan." },
  { no: 72, arabic: "الْمُؤَخِّرُ", turkish: "El-Muahhir", meaning: "Dilediğini geriye bırakan." },
  { no: 73, arabic: "الْأَوَّلُ", turkish: "El-Evvel", meaning: "Başlangıcı olmayan, ilk olan." },
  { no: 74, arabic: "الْآخِرُ", turkish: "El-Âhir", meaning: "Sonu olmayan, son olan." },
  { no: 75, arabic: "الظَّاهِرُ", turkish: "Ez-Zâhir", meaning: "Varlığı apaçık olan." },
  { no: 76, arabic: "الْبَاطِنُ", turkish: "El-Bâtın", meaning: "Zatı akıllarla kavranamayan." },
  { no: 77, arabic: "الْوَالِي", turkish: "El-Vâlî", meaning: "Kâinatı yöneten." },
  { no: 78, arabic: "الْمُتَعَالِي", turkish: "El-Müte'âlî", meaning: "Yaratılmışların vasıflarından uzak, yüce." },
  { no: 79, arabic: "الْبَرُّ", turkish: "El-Berr", meaning: "İyilik ve ihsanı bol olan." },
  { no: 80, arabic: "التَّوَّابُ", turkish: "Et-Tevvâb", meaning: "Tövbeleri çokça kabul eden." },
  { no: 81, arabic: "الْمُنْتَقِمُ", turkish: "El-Müntekim", meaning: "Adaleti gereği zalimden hesap soran." },
  { no: 82, arabic: "الْعَفُوُّ", turkish: "El-Afüvv", meaning: "Günahları silen, çokça affeden." },
  { no: 83, arabic: "الرَّءُوفُ", turkish: "Er-Raûf", meaning: "Kullarına çok şefkatli olan." },
  { no: 84, arabic: "مَالِكُ الْمُلْكِ", turkish: "Mâlikü'l-Mülk", meaning: "Mülkün gerçek sahibi." },
  { no: 85, arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", turkish: "Zü'l-Celâli ve'l-İkrâm", meaning: "Ululuk ve ikram sahibi." },
  { no: 86, arabic: "الْمُقْسِطُ", turkish: "El-Muksit", meaning: "Adaletle hükmeden." },
  { no: 87, arabic: "الْجَامِعُ", turkish: "El-Câmi'", meaning: "Dağınık olanı bir araya getiren." },
  { no: 88, arabic: "الْغَنِيُّ", turkish: "El-Ganiyy", meaning: "Zengin, hiçbir şeye muhtaç olmayan." },
  { no: 89, arabic: "الْمُغْنِي", turkish: "El-Muğnî", meaning: "Dilediğini zengin kılan." },
  { no: 90, arabic: "الْمَانِعُ", turkish: "El-Mâni'", meaning: "Dilediğinin önüne engel koyan." },
  { no: 91, arabic: "الضَّارُّ", turkish: "Ed-Dârr", meaning: "Hikmeti gereği zarar veren." },
  { no: 92, arabic: "النَّافِعُ", turkish: "En-Nâfi'", meaning: "Fayda veren." },
  { no: 93, arabic: "النُّورُ", turkish: "En-Nûr", meaning: "Nurun kaynağı, aydınlatan." },
  { no: 94, arabic: "الْهَادِي", turkish: "El-Hâdî", meaning: "Doğru yolu gösteren." },
  { no: 95, arabic: "الْبَدِيعُ", turkish: "El-Bedî'", meaning: "Örneksiz ve eşsiz yaratan." },
  { no: 96, arabic: "الْبَاقِي", turkish: "El-Bâkî", meaning: "Varlığı ebedî olan." },
  { no: 97, arabic: "الْوَارِثُ", turkish: "El-Vâris", meaning: "Her şeyin gerçek sahibi, her şey O'na kalır." },
  { no: 98, arabic: "الرَّشِيدُ", turkish: "Er-Reşîd", meaning: "İşlerini hikmetle sonuca ulaştıran." },
  { no: 99, arabic: "الصَّبُورُ", turkish: "Es-Sabûr", meaning: "Cezada acele etmeyen, sabreden." },
];
